CREATE TABLE CLIENTE_CLI(
CLI_CODIGO INT PRIMARY KEY IDENTITY,
CLI_NOME_COMPLETO VARCHAR(50),
CLI_ENDERECO VARCHAR(100),
CLI_NUMERO VARCHAR(6),
CLI_COMPLEMENTO VARCHAR(50),
CLI_BAIRRO VARCHAR(50),
CLI_CEP VARCHAR(8),
CLI_CPF VARCHAR(11),
CLI_EMAIL VARCHAR(50),
CLI_USUARIO VARCHAR(50),
CLI_SENHA VARCHAR(20)
)

CREATE TABLE TIPO_TELEFONE_TTE(
TTE_CODIGO INT PRIMARY KEY IDENTITY,
TTE_DESCRICAO VARCHAR(20)
)

CREATE TABLE TELEFONE_TEL(
TEL_CODIGO INT PRIMARY KEY IDENTITY,
TEL_NUMERO VARCHAR(11),
TTE_CODIGO INT FOREIGN KEY (TTE_CODIGO) REFERENCES TIPO_TELEFONE_TTE,
CLI_CODIGO INT FOREIGN KEY (CLI_CODIGO) REFERENCES CLIENTE_CLI
)

CREATE TABLE TIPO_STATUS_TST(
TST_CODIGO INT PRIMARY KEY IDENTITY,
TST_DESCRICAO VARCHAR(50)
)

CREATE TABLE STATUS_SERVICO_SSE(
SSE_CODIGO INT PRIMARY KEY IDENTITY,
SSE_DESCRICAO VARCHAR(50),
SSE_DATA_HORA_ENTRADA DATETIME,
SSE_DATA_HORA_SAIDA DATETIME,
TST_CODIGO INT FOREIGN KEY (TST_CODIGO) REFERENCES TIPO_STATUS_TST,
CLI_CODIGO INT FOREIGN KEY (CLI_CODIGO) REFERENCES CLIENTE_CLI
)

CREATE TABLE TIPO_SERVICO_TSE(
TSE_CODIGO INT PRIMARY KEY IDENTITY,
TSE_DESCRICAO VARCHAR (20)
)

CREATE TABLE SERVICO_SER(
SER_CODIGO INT PRIMARY KEY IDENTITY,
SER_NOME VARCHAR(50),
SER_VALOR MONEY,
TSE_CODIGO INT FOREIGN KEY (TSE_CODIGO) REFERENCES TIPO_SERVICO_TSE
)

CREATE TABLE AGENDAMENTO_AGE(
AGE_CODIGO INT PRIMARY KEY IDENTITY,
AGE_VALOR MONEY,
AGE_DATA_HORA_ENTRADA DATETIME,
AGE_DATA_HORA_SAIDA DATETIME,
SER_CODIGO INT FOREIGN KEY (SER_CODIGO) REFERENCES SERVICO_SER,
SSE_CODIGO INT FOREIGN KEY (SSE_CODIGO) REFERENCES STATUS_SERVICO_SSE,
CLI_CODIGO INT FOREIGN KEY (CLI_CODIGO) REFERENCES CLIENTE_CLI
)




